/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2025 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-aarch64"
#define DATE "built on: Wed Oct 29 08:56:26 2025 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','~','/','i','m','m','o',
    'r','t','a','l','_','b','u','i','l','d','/','i','m','m','o','r',
    't','a','l','w','r','t','-','t','o','o','l','c','h','a','i','n',
    '-','2','4','.','1','0','.','3','-','b','c','m','2','7','x','x',
    '-','b','c','m','2','7','1','1','_','g','c','c','-','1','3','.',
    '3','.','0','_','m','u','s','l','.','L','i','n','u','x','-','x',
    '8','6','_','6','4','/','t','o','o','l','c','h','a','i','n','-',
    'a','a','r','c','h','6','4','_','c','o','r','t','e','x','-','a',
    '7','2','_','g','c','c','-','1','3','.','3','.','0','_','m','u',
    's','l','/','b','i','n','/','a','a','r','c','h','6','4','-','o',
    'p','e','n','w','r','t','-','l','i','n','u','x','-','m','u','s',
    'l','-','g','c','c',' ','-','f','P','I','C',' ','-','p','t','h',
    'r','e','a','d',' ','-','W','a','l','l',' ','-','O','3',' ','-',
    'D','O','P','E','N','S','S','L','_','U','S','E','_','N','O','D',
    'E','L','E','T','E',' ','-','D','O','P','E','N','S','S','L','_',
    'P','I','C',' ','-','D','O','P','E','N','S','S','L','_','B','U',
    'I','L','D','I','N','G','_','O','P','E','N','S','S','L',' ','-',
    'D','N','D','E','B','U','G','\0'
};
